package topology

import (
	"strings"

	k8score "github.com/skyhook-io/radar/pkg/k8score"
)

// ClusterScopedKindEntry maps a topology NodeKind for a cluster-scoped
// resource to the (group, resource) tuple a SubjectAccessReview needs to
// authorize a list/get.
type ClusterScopedKindEntry struct {
	Kind     NodeKind
	Group    string
	Resource string
}

// ClusterScopedKinds is the central denylist of cluster-scoped kinds the
// topology builder synthesizes. Both the topology-strip path (REST + MCP)
// and the neighborhood per-node RBAC gate iterate this table; centralising
// it removes the historical "update BOTH internal/server and internal/mcp"
// drift hazard that the checklist on NodeKind warned about.
//
// KindNamespace is intentionally excluded — handled by per-user filter
// upstream. KindNodeClass has one entry per cloud provider (EC2 / AKS /
// GCP) because the topology builder iterates them under the same NodeKind
// label; callers should treat ALL three as a single SAR-anchored gate so
// providers absent from cluster discovery don't over-deny.
var ClusterScopedKinds = []ClusterScopedKindEntry{
	{KindNode, "", "nodes"},
	{KindNodePool, "karpenter.sh", "nodepools"},
	{KindNodeClaim, "karpenter.sh", "nodeclaims"},
	{KindNodeClass, "karpenter.k8s.aws", "ec2nodeclasses"},
	{KindNodeClass, "karpenter.azure.com", "aksnodeclasses"},
	{KindNodeClass, "karpenter.k8s.gcp", "gcenodeclasses"},
	{KindGatewayClass, "gateway.networking.k8s.io", "gatewayclasses"},
	{KindPV, "", "persistentvolumes"},
	{KindStorageClass, "storage.k8s.io", "storageclasses"},
	{KindCiliumClusterwideNetworkPolicy, "cilium.io", "ciliumclusterwidenetworkpolicies"},
	{KindClusterNetworkPolicy, "policy.networking.k8s.io", "clusternetworkpolicies"},
}

// SARTuple is a (group, resource, namespace) triple suitable for handing to
// a SubjectAccessReview. Used as the return type of the neighborhood RBAC
// tuple-selection helpers below so REST + MCP can iterate the same set of
// candidates through their respective per-user check function without
// duplicating the table-walking + discovery-filter logic.
type SARTuple struct {
	Group     string
	Resource  string
	Namespace string
}

// PseudoKindDiscoveryLookup is the minimal discovery surface
// RBACTuplesForKind uses to drop pseudo-kind variants whose CRD has been
// removed mid-build (or never installed). Pass nil to skip the filter — the
// helper then returns every (kind, group)-matched row unfiltered, matching
// the over-include-on-missing-discovery behavior the REST + MCP per-node
// gates already used before this extraction.
//
// A function type (rather than an interface) sidesteps the Go nil-interface
// gotcha: callers commonly write `disc := k8s.GetResourceDiscovery()` which
// can return a typed-nil pointer that lifts into a non-nil interface — the
// in-helper `disc != nil` check then passes but the method call panics on
// the autogenerated forwarder for the embedded discovery pointer. With a
// function type, callers can pass the bound method (`disc.GetResourceWithGroup`)
// when the pointer is concrete and nil when it isn't, with a single `if`.
type PseudoKindDiscoveryLookup func(resource, group string) (k8score.APIResource, bool)

// RBACTuplesForKind returns the SAR tuples authorizing a read of the given
// cluster-scoped topology pseudo-kind. Centralises the table-walking +
// discovery-filter logic that previously lived in four parallel helpers
// (canReadClusterScopedTopoKind{,MCP} + canReadClusterScopedTopoKindByName{,MCP}).
//
// `group` semantics:
//   - Non-empty (per-node path: pass the node's apiVersion group) → returns
//     ONLY the row matching that group. For pseudo-kinds like NodeClass this
//     disambiguates EC2 / AKS / GCP variants so a user with one provider's
//     RBAC doesn't pick up another provider's nodes.
//   - Empty (root-preflight path: caller has URL kind only) → returns ALL
//     rows under the kind so caller can SAR each and allow on first pass.
//
// Return semantics — three states, in order of caller decision:
//
//   - tracked=false: kind isn't in ClusterScopedKinds. Caller should fall
//     back to k8s.ClassifyKindScope (the regular static-catalogue +
//     discovery path). Both surfaces already do this.
//   - tracked=true + len(tuples) > 0: caller iterates tuples through its
//     protocol-specific per-user check (REST: s.canRead; MCP:
//     canReadInNamespace) and ALLOWS on the first pass.
//   - tracked=true + len(tuples) == 0 + fallthroughAllow=true: every
//     candidate row was eliminated by the discovery filter (CRD removed
//     mid-build, or no provider variant installed on this cluster). Caller
//     should ALLOW — matches the pre-existing "over-include rather than
//     silently hide a node the cluster admin can see" behavior the per-node
//     and by-name helpers both used.
//   - tracked=true + len(tuples) == 0 + fallthroughAllow=false: kind IS
//     tracked but no row matched the supplied group. Caller should DENY —
//     this is the per-variant safety the helpers exist to enforce. Only
//     possible when group is non-empty (root-preflight passes empty group
//     and gets every row).
//
// Discovery filter: rows with a non-empty Group whose (Resource, Group) is
// MISSING from disc are skipped. Rows with empty Group (core/v1 kinds like
// Node, PV) are kept regardless — those don't ride on CRD discovery. nil
// disc disables the filter and returns every matching row.
//
// The returned slice is a fresh allocation — callers may mutate.
func RBACTuplesForKind(kind, group string, disc PseudoKindDiscoveryLookup) (tuples []SARTuple, tracked bool, fallthroughAllow bool) {
	// Resolve pseudo-kinds (e.g. KnativeService → ServingService) so the
	// caller-supplied (kind, group) lines up with the ClusterScopedKinds
	// table's Pascal-cased rows. ClusterScopedKinds contains only
	// cluster-scoped entries; namespaced pseudo-kinds (KnativeService,
	// CAPICluster, …) correctly fail the lookup and the caller falls back.
	resolved := pseudoKindFor(kind, group)

	// tracked := the kind appears in ClusterScopedKinds at all. We need this
	// signal separately from "matched a row under the supplied group" so the
	// per-variant deny case (tracked + supplied group doesn't match any row)
	// is distinguishable from the not-tracked case (caller should fall
	// through to ClassifyKindScope).
	for _, ck := range ClusterScopedKinds {
		if strings.EqualFold(string(ck.Kind), resolved) {
			tracked = true
			break
		}
	}
	if !tracked {
		return nil, false, false
	}

	// Caller-supplied group selects a specific variant; empty group returns
	// every variant under the kind.
	for _, ck := range ClusterScopedKinds {
		if !strings.EqualFold(string(ck.Kind), resolved) {
			continue
		}
		if group != "" && ck.Group != group {
			continue
		}
		if ck.Group != "" && disc != nil {
			if _, ok := disc(ck.Resource, ck.Group); !ok {
				continue
			}
		}
		tuples = append(tuples, SARTuple{Group: ck.Group, Resource: ck.Resource, Namespace: ""})
	}
	if len(tuples) > 0 {
		return tuples, true, false
	}

	// Tracked + zero tuples: distinguish "every row was filtered by
	// discovery" (fallthroughAllow=true) from "no row matched supplied
	// group" (fallthroughAllow=false, per-variant deny).
	if group == "" {
		// Empty group means we walked every row under the kind; if none
		// survived the filter, the disc lookup dropped them all → fallthrough-allow.
		return nil, true, true
	}
	// group != "" → re-walk WITHOUT the disc filter. If a row exists
	// pre-filter, the filter ate it → fallthrough-allow. Else no row
	// matched group → per-variant deny.
	for _, ck := range ClusterScopedKinds {
		if !strings.EqualFold(string(ck.Kind), resolved) {
			continue
		}
		if ck.Group == group {
			// Pre-filter row exists for the requested group → disc filter
			// removed it → over-include the same way the existing per-node
			// gate did when its single targeted row failed discovery.
			return nil, true, true
		}
	}
	// No row exists for (kind, group) — deny.
	return nil, true, false
}

// NodeRBACDecision is the verdict RBACTuplesForNode returns to the caller.
// Four states cover every code path the per-node gate used to handle inline;
// the caller dispatches on Decision and (when applicable) iterates Tuples
// through its protocol-specific per-user check.
type NodeRBACDecision int

const (
	// NodeRBACAllow: the caller should ALLOW the read without testing any
	// SAR tuple. Tuples is empty. Cases:
	//   - Namespaced node whose namespace-list gate is a sufficient signal
	//     (ordinary kinds — Pod, ConfigMap, …).
	//   - Cluster-scoped pseudo-kind whose only matching variant was filtered
	//     out by discovery (CRD removed mid-build / not installed).
	NodeRBACAllow NodeRBACDecision = iota

	// NodeRBACDeny: the caller should DENY the read without testing any
	// SAR tuple. Tuples is empty. Single case today:
	//   - Cluster-scoped pseudo-kind whose node carries an apiVersion-group
	//     not in the per-variant table — over-deny rather than leak an
	//     unmapped variant.
	NodeRBACDeny

	// NodeRBACCheckTuples: the caller should iterate Tuples through its
	// per-user SAR function and allow on the FIRST passing tuple. Cases:
	//   - Namespaced Secret node (Tuples = [{"", "secrets", ns}]).
	//   - Cluster-scoped pseudo-kind node with a matching variant row
	//     (Tuples = [{table.Group, table.Resource, ""}]).
	NodeRBACCheckTuples

	// NodeRBACConsultClassifyKindScope: the caller should fall back to the
	// regular k8s.ClassifyKindScope path. Tuples is empty. Single case:
	//   - Cluster-scoped node that is NOT a tracked pseudo-kind. The
	//     helper deliberately doesn't call into the k8s package (which is
	//     internal and would create an import cycle); the caller already
	//     has ClassifyKindScope in scope.
	NodeRBACConsultClassifyKindScope
)

// RBACTuplesForNode is the per-node equivalent of RBACTuplesForKind. Given
// a topology node, classifies the read into one of four decisions and (when
// applicable) returns the SAR tuples to test. Mirrors the now-collapsed
// canReadNeighborhoodNode{,MCP} table-selection logic so REST + MCP share
// one source of truth.
//
// CALLER CONTRACT: when n has a non-empty namespace, the caller must first
// run its protocol-specific namespace-list gate (REST: getUserNamespaces;
// MCP: checkNamespaceAccess). RBACTuplesForNode does NOT encode that gate
// — it's per-user state the helper doesn't see. The returned decision
// applies AFTER the namespace gate has passed.
//
// Decision summary:
//
//   - Namespaced, n.Kind == KindSecret → CheckTuples with the per-namespace
//     secrets tuple. Secret nodes need a per-user secrets SAR because the
//     cache SA may have cluster-wide secrets RBAC the calling user doesn't.
//   - Namespaced, other kinds → Allow.
//   - Cluster-scoped, tracked pseudo-kind, variant matches → CheckTuples
//     with the per-variant cluster-scope tuple.
//   - Cluster-scoped, tracked pseudo-kind, disc filter ate the row → Allow.
//   - Cluster-scoped, tracked pseudo-kind, unmapped variant → Deny.
//   - Cluster-scoped, NOT a tracked pseudo-kind → ConsultClassifyKindScope.
func RBACTuplesForNode(n *Node, disc PseudoKindDiscoveryLookup) (decision NodeRBACDecision, tuples []SARTuple) {
	if n == nil {
		// Defensive: nil node can't be authorized.
		return NodeRBACDeny, nil
	}
	ns := nodeNamespaceFromData(n)
	if ns != "" {
		if n.Kind == KindSecret {
			return NodeRBACCheckTuples, []SARTuple{{Group: "", Resource: "secrets", Namespace: ns}}
		}
		return NodeRBACAllow, nil
	}

	// Cluster-scoped. Try the pseudo-kind table first.
	group := nodeAPIGroupFromData(n)
	pseudoTuples, tracked, fallthroughAllow := RBACTuplesForKind(string(n.Kind), group, disc)
	if !tracked {
		return NodeRBACConsultClassifyKindScope, nil
	}
	if len(pseudoTuples) > 0 {
		return NodeRBACCheckTuples, pseudoTuples
	}
	if fallthroughAllow {
		return NodeRBACAllow, nil
	}
	return NodeRBACDeny, nil
}

